// This file was automatically generated by VS extension Windows Machine Learning Code Generator VS 2017 v2.6
// from model file aussie_animals.onnx
// Warning: This file may get overwritten if you add add an onnx file with the same name
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Windows.Media;
using Windows.Storage;
using Windows.Storage.Streams;
using Windows.AI.MachineLearning;
namespace IntelligentKioskSample
{
    
    public sealed class aussie_animalsInput
    {
        public ImageFeatureValue data; // BitmapPixelFormat: Bgra8, BitmapAlphaMode: Premultiplied, width: 416, height: 416
    }
    
    public sealed class aussie_animalsOutput
    {
        public TensorFloat model_outputs0; // shape(-1,40,13,13)
    }
    
    public sealed class aussie_animalsModel
    {
        private LearningModel model;
        private LearningModelSession session;
        private LearningModelBinding binding;
        public static async Task<aussie_animalsModel> CreateFromStreamAsync(IRandomAccessStreamReference stream)
        {
            aussie_animalsModel learningModel = new aussie_animalsModel();
            learningModel.model = await LearningModel.LoadFromStreamAsync(stream);
            learningModel.session = new LearningModelSession(learningModel.model);
            learningModel.binding = new LearningModelBinding(learningModel.session);
            return learningModel;
        }
        public async Task<aussie_animalsOutput> EvaluateAsync(aussie_animalsInput input)
        {
            binding.Bind("data", input.data);
            var result = await session.EvaluateAsync(binding, "0");
            var output = new aussie_animalsOutput();
            output.model_outputs0 = result.Outputs["model_outputs0"] as TensorFloat;
            return output;
        }
    }
}

